### ISSUE TITLE
Fix Select Atoms in Relax Calculation

### ISSUE THREAD

**Issue by mikeatm** [aiidateam/aiida-quantumespresso#1023]
QE supports fixing atomic positions, (see  [here](https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm1493) [and here](https://lists.quantum-espresso.org/pipermail/users/2006-May/004215.html) ) i saw its mentioned somewhere in aiida-core [here](https://aiida.readthedocs.io/projects/aiida-core/en/v0.8.1/plugins/quantumespresso/pw.html#fixing-some-atom-coordinates)  as well ,  is there any more documentation for this in aiida-quantumespresso?

**Comment by sphuber** [comment]
https://aiida-quantumespresso.readthedocs.io/en/latest/howto/calculations/pw.html#how-to-fix-the-coordinates-of-atoms
