### ISSUE TITLE
Bugs with HubbardStructureData when using molecules 

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidateam/aiida-quantumespresso#1053]
when trying to set up HubbardParameters with a molecule for DFT+U  , there is this error , 

hubbard_structure.initialize_onsites_hubbard(
    144                     atom_name=kind,
    145                     atom_manifold=orbital,

~/.local/lib/python3.9/site-packages/aiida_quantumespresso/data/hubbard_structure.py in initialize_onsites_hubbard(self, atom_name, atom_manifold, value, hubbard_type, use_kinds)
    223         for atom_index in atom_indices:
    224             args = (atom_index, atom_manifold, atom_index, atom_manifold, value, [0, 0, 0], hubbard_type)
--> 225             self.append_hubbard_parameter(*args)
    226 
    227     def _get_one_kind_index(self, kind_name: str) -> List[int]:

~/.local/lib/python3.9/site-packages/aiida_quantumespresso/data/hubbard_structure.py in append_hubbard_parameter(self, atom_index, atom_manifold, neighbour_index, neighbour_manifold, value, translation, hubbard_type)
    131 
    132         hp_tuple = (atom_index, atom_manifold, neighbour_index, neighbour_manifold, value, translation, hubbard_type)
--> 133         parameters = HubbardParameters.from_tuple(hp_tuple)
    134         hubbard = self.hubbard
    135 

~/.local/lib/python3.9/site-packages/aiida_quantumespresso/common/hubbard.py in from_tuple(hubbard_parameters)
    106             'hubbard_type',
    107         ]
--> 108         return HubbardParameters(**dict(zip(keys, hubbard_parameters)))
    109 
    110 

/opt/conda/lib/python3.9/site-packages/pydantic/main.py in __init__(self, **data)
    173         # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    174         __tracebackhide__ = True
--> 175         self.__pydantic_validator__.validate_python(data, self_instance=self)
    176 
    177     # The following line sets a flag that we use to determine when `__init__` gets overridden by the user

ValidationError: 2 validation errors for HubbardParameters
atom_manifold
  Value error, invalid length ``4``. Only 2 or 5. [type=value_error, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
neighbour_manifold
  Value error, invalid length ``4``. Only 2 or 5. [type=value_error, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error

**Comment by AndresOrtegaGuerrero** [comment]
@bastonero

**Comment by bastonero** [comment]
Hi Andres, 
Thanks for the feedback. Nevertheless, it doesn't seem like a bug. Look at the traceback (I highlighted some of it):
```
ValidationError: 2 validation errors for HubbardParameters
**atom_manifold**
**Value error, invalid length 4. Only 2 or 5.** [type=value_error, input_value='None', input_type=str]
```
It seems your input contains an `atom_manifold` with length 4, which is weird. Could you post your input please?

You should input either something like `3d` or `3d-2p`, this is why the length should be either 2 or 5. I don't understand why you have a string with 4 chars.

**Comment by AndresOrtegaGuerrero** [comment]
Yes, I notice there was a typo in the manifold in the app , my bad i will close this issue , thank you @bastonero
