### ISSUE TITLE
Revisit the examples in examples/submission/quantum_espresso/

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-quantumespresso#131]
- [ ] Move examples one level up
- [ ] Adapt them (in the workflows branch, towards 3.0) to use the new `builder` logic rather than the old-style submission method.

**Comment by sphuber** [comment]
I was taking a look at these old examples and was wondering whether it would maybe be better to convert them into a cli command such as I already implemented for `PwCalculation` in `aiida-quantumespresso.cli.calculations.pw.base`. The advantage I can see is that it will reduce the maintenance for the developers as a lot of boilerplate is taken away. Moreover this makes it easier to run for users, as the variables are passable from the command line without having to change the scripts. The only downside I can see is that the implementation of the cli command might obscure some of the work, such as defining some of the inputs which will partially be taken care of by the predefined click options. But I am not sure if that too much of a problem as I think users that use these should be familiar with creating basic inputs like `StructureData` and `KpointsData` and should not be the purpose of these examples. What do you reckon?
