### ISSUE TITLE
Implement the new `multidimensional` tag of input xml specification for pw.x in helpers

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#188]
The new XML input specification of pw.x will have proper support for multidimensional variables such as `Hubbard_J` and `starting_ns_eigenvalues`. The helpers should be updated to be able to parse and validate input dictionaries against these spec tags.

**Comment by borellim** [comment]
@sphuber where can I find more info on this XML input format? Is it the same as the output format? Do we need this for v3.0?

**Comment by sphuber** [comment]
I already fixed this issue more or less and have it in a branch, so don't work on this yet. We will discuss this on Monday and then we can look at the branch
