### ISSUE TITLE
The documentation of pwimmigration doesn't fit to the latest version

### ISSUE THREAD

**Issue by quanshengwu** [aiidateam/aiida-quantumespresso#195]
Could developers update the documentation of the pwimmigration of the latest version?

https://aiida-quantumespresso.readthedocs.io/en/latest/user_guide/get_started/examples/pwimmigrant_tutorial.html?highlight=pwimmigrant

**Comment by chrisjsewell** [comment]
Hi @quanshengwu I was about to follow this tutorial. Could you tell me what issues you had when using it with the latest version?

**Comment by chrisjsewell** [comment]
@quanshengwu read my comment above; you just use `transport = computer.get_transport()`. But, as dicussed in aiidateam/aiida_core#1892, currently in v1 you can only create inputs from this process, not outputs (which can be created using v0.12)

**Comment by quanshengwu** [comment]
@chrisjsewell 

Thanks. It works now.
