### ISSUE TITLE
_prepare_for_submission NotImplementedError

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-quantumespresso#196]
I have just installed aiida today and tried to run the [PWscf example](http://aiida-quantumespresso.readthedocs.io/en/latest/user_guide/get_started/examples/pw_tutorial.html#compact-script), but I get the following error:

```
[2018-08-15 11:42:45,412: WARNING/Worker-3] 08/15/2018 11:42:45 AM, aiida.execmanager: [ERROR] Submission of calc 13 failed, check also the log file! Traceback: Traceback (most recent call last):
  File "//anaconda/envs/aiida/lib/python2.7/site-packages/aiida/daemon/execmanager.py", line 475, in submit_calc
    folder, use_unstored_links=False)
  File "//anaconda/envs/aiida/lib/python2.7/site-packages/aiida/orm/implementation/general/calculation/job/__init__.py", line 1472, in _presubmit
    calcinfo = self._prepare_for_submission(folder, inputdict)
  File "//anaconda/envs/aiida/lib/python2.7/site-packages/aiida/orm/implementation/general/calculation/job/__init__.py", line 1255, in _prepare_for_submission
    raise NotImplementedError
```

Have I done something wrong?! As you can see, I've installed everything within a Conda environment, and here are the versions:

    aiida-core                0.12.1                    <pip>
    aiida-quantumespresso     2.1.0                     <pip>

I was attempting to run the calculation on a HPC with PBSpro. Let me know if there is any other details I can give you. Thanks in advance.

**Comment by sphuber** [comment]
Could you please run the following in a `verdi shell` and report the output to me:
```
codename = '' # Put the name of the code here that you used for the example
n = load_node(13)
print n.type
code = Code.get_from_string(codename)
print code.get_attr('input_plugin')
```
And also run `verdi calculation plugins`

**Comment by chrisjsewell** [comment]
```
* ase.ase
* quantumespresso.cp
* quantumespresso.dos
* quantumespresso.matdyn
* quantumespresso.namelists
* quantumespresso.neb
* quantumespresso.ph
* quantumespresso.pp
* quantumespresso.projwfc
* quantumespresso.pw
* quantumespresso.pw2wannier90
* quantumespresso.pwimmigrant
* quantumespresso.q2r
* simpleplugins.templatereplacer
```

```python
In [3]: print n.type
calculation.job.quantumespresso.pw.PwCalculation.

In [4]: print code.get_attr('input_plugin')
quantumespresso.pw
```

**Comment by sphuber** [comment]
OK, that all seems fine. Maybe the daemon was started before the `aiida-quantumespresso` plugin was installed. Please run in a normal shell:
```
reentry scan
verdi daemon stop
verdi daemon start
```

and then try to run the example again

**Comment by chrisjsewell** [comment]
That totally worked thanks, I knew it was going to be something dumb!
One other issue I have now is getting the qsub to meet the spec required by the HPC's scheduler.
Using:

```python
calc.set_resources({"num_machines": 1,"num_cores_per_machine": 16})
calc.set_max_memory_kb = 1*10e6
``` 

I get the error:

```
|   stderr=qsub: Invalid -lselect syntax. :['1:mpiprocs=16:ppn=16']
|        The correct format is -lselect=N:ncpus=X:mem=Ygb , optionally including ompthreads=A:mpiprocs=B
```

Do you know of a simple way to fix this without digging into the code?

**Comment by sphuber** [comment]
I am not too familiar with the scheduler plugins, but if that is a real bug, it would be a problem for `aiida-core and so would be best to open an issue there. It might be related to the version of Torque that the  cluster is running, that is not supported by the scheduler plugin in `aiida-core`.

**Comment by chrisjsewell** [comment]
No problem, thanks anyway

**Comment by chrisjsewell** [comment]
FYI, I just created a new scheduler in the plugin folder and `reentry scan` read it in :)
