### ISSUE TITLE
QE 6.3 incorrectly prints total wall-time: add workaround?

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#201]
A bug introduced in QE 6.3 causes an incorrect printout of the final wall-clock time, when it is >=1 hour and <1 day. The bug was fixed at [this commit](https://gitlab.com/QEF/q-e/commit/29164dbf9ab97a7e6e4be04ac3ae1fa721b8871b) (notice line 438), and backported in a separate branch [qe-6.3-backports](https://gitlab.com/QEF/q-e/tree/qe-6.3-backports) that may or may not be released in the future as QE 6.3.1. In any case, those using QE 6.3  will have incorrect wall-clock times and will not realise it.

**Should the aiida-quantumespresso parser implement a workaround for this bug?**

Here is an example of incorrect printout. The time is printed as `26h 6m WALL` when it should be `6h 35m WALL`. The `26` is taken from the minutes of the CPU time, and the `35` is printed two lines later as `35h`.

```
[...]

     Parallel routines
     fft_scatt_xy :   1444.20s CPU   1450.47s WALL ( 2091265 calls)
     fft_scatt_yz :    830.14s CPU    833.77s WALL ( 2091265 calls)
 
     PWSCF        :     6h26m CPU       26h 6m WALL

      35h
 
   This run was terminated on:  19: 8:16  29Aug2018    
```

**Comment by mbercx** [comment]
Since we now dropped support for anything below QE < v7.0. I'm closing this. :)
