### ISSUE TITLE
Allow tests to compare contents of files

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#209]
In CI tests, it's currently only possible to check attributes, not the contents of files. For instance, one can only verify the size of a numpy array, not its contents, as the contents are stored as .npy files.

**Comment by sphuber** [comment]
This is possible now with the new dependency `python-regressions`. In PR #302 you can see an example where I am comparing the input written by `PwCalculation.prepare_for_submission`:
```
with fixture_sandbox_folder.open('aiida.in') as handle:
        input_written = handle.read()
# Checks on the files written to the sandbox folder as raw input
assert sorted(fixture_sandbox_folder.get_content_list()) == sorted(['aiida.in', 'pseudo', 'out'])
file_regression.check(input_written, encoding='utf-8', extension='.in')
```
