### ISSUE TITLE
Restart breaks if a calculation is killed by the scheduler after 'Maximum CPU time exceeded' but before finishing saving

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#225]
A PW calculation can be killed by the scheduler after printing 'Maximum CPU time exceeded' to aiida.out, but before it finishes to save the current state. In this case, the PwBaseWorkChain handles the error with `_handle_error_exceeded_maximum_walltime`, in which it sets a `restart_calc`, but the next restart calculation will fail as some data are missing.

This has happened with a very short total time (100s (scheduler) / 95s (PW input)).

We should try to check whether the output data of the previous calculation are correct (as far as reasonable), and if not, make a `from_scratch` calculation instead (not a restart) with a lower `delta_factor_max_seconds`.

Workarounds are to either set a larger max walltime (which will proportionally allow for a larger margin for saving) or change `delta_factor_max_seconds` to a smaller value here: https://github.com/aiidateam/aiida-quantumespresso/blob/79007b44b229170e9c12c4c679aa03e46e5499c6/aiida_quantumespresso/workflows/pw/base.py#L37-L43

See also the Google Groups discussion: https://groups.google.com/d/topic/aiidausers/dzzzDfo6qQ4/discussion

**Comment by sphuber** [comment]
Addressed in PR #360
