### ISSUE TITLE
Add XML schema for QE-GPU v6.4a1

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#260]
QE-GPU v6.4a1 ([home page](https://gitlab.com/QEF/q-e-gpu/wikis/home), [releases](https://gitlab.com/QEF/q-e-gpu/releases)), which is based on QE 6.4rc (i.e. [this commit](https://gitlab.com/QEF/q-e/commit/335abfac7c2c65b0066d19741d1a0a2b91882600), not the actual release of QE 6.4), outputs an XML file with a schema location of "http://www.quantum-espresso.org/ns/qes/qes_190207.xsd". This schema is not available from the QE website, but I have a copy. The only difference between my copy of this file and the current latest schema (qes_190304.xsd) is:
```
$ diff qes_190304.xsd qes_190207.xsd 
789c789
<       <element type="integer" name="n_opt_steps"/>
---
>       <element type="positiveInteger" name="n_opt_steps"/>
```

However this is an error: `n_opt_steps` should indeed be an integer, and this schema does not correctly validate the file. Therefore, we should simply use qes_190304.xsd, just with a different name of qes_190207.xsd.

**Comment by sphuber** [comment]
I would still propose to only add schema's for actual releases to the repository and not those of pre-releases. For testing and development purposes the schema can be added locally to the repository. With the change I made recently, the parser will now auto discover any schema that is added to the schema directory

**Comment by borellim** [comment]
As I understand it, QE-GPU will drop the "alpha" tag only when all parts of QE have stable GPU support, which will probably take a while (source: https://gitlab.com/QEF/q-e-gpu/wikis/home#versioning). Of course we can decide not to support QE-GPU at all.

I was also wondering if we could just add `qes_190207.xsd` as a symbolic link, since it's identical to `qes_190304.xsd`. (This is a memo for myself to try.)

**Comment by sphuber** [comment]
As we agreed recently in a discussion, we will only be adding the schema files of actual releases. Not pre-releases. So I am closing this

**Comment by borellim** [comment]
Good news: the latest version of QE-GPU (`6.4.1a1`) seems to be using the schema `qes_190304.xsd`, so it should be automatically supported  by aiida-qe. I haven't tested it though.
