### ISSUE TITLE
run_init() in PwBaseWorkChain does not work in aiida 1.0

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#264]
`PwCalculation.process()` does not exist.

Use as a model the method `run_calculation()` in `BaseRestartWorkChain`.

**Comment by sphuber** [comment]
`process` is a property, so simply get rid of the parentheses should make it work

**Comment by borellim** [comment]
Actually it seems that the `process` attribute was removed altogether, and I should use `PwCalculation` directly. It works (the calculation is launched), but we now have problems parsing an "init-only" calculation...
