### ISSUE TITLE
Remove classproperty usages

### ISSUE THREAD

**Issue by odarbelaeze** [aiidateam/aiida-quantumespresso#270]
I would like to remove the usages of `@classproperty`, in favor of the `@classmethod` language feature, the implementation would go from:

```python
@classproperty
def _FILE_XML_PRINT_COUNTER_BASENAME(cls):
    return 'print_counter.xml'
```

to

```python
@classmethod
def _xml_print_counter_basename(cls):
    return 'print_counter.xml' or cls.spec.input....
```

The usages might be updated accordingly.

**Comment by sphuber** [comment]
Any particular reason why you want to get rid of it?

**Comment by odarbelaeze** [comment]
The result could be achieved with language features `classmethod` or in some instances `property`. The linters complain about it:

![Screenshot from 2019-04-29 17-51-58](https://user-images.githubusercontent.com/1621518/56909069-ce049400-6aa7-11e9-9d11-8af46b44563b.png)

and finally, I'm not sure it's "isomorphic" to the `@property` decorator, which makes it a little bit confusing, as I cannot write:

```python
    @classproperty
    def xml_filepaths(cls):
        """Returns a list of relative filepaths of XML files."""
        filepaths = []

        for filename in cls.xml_filenames:
            filepath = os.path.join(
                cls._OUTPUT_SUBFOLDER,
                "{}_{}.save".format(cls._PREFIX, cls._CP_WRITE_UNIT_NUMBER),
                filename,
            )
            filepaths.append(filepath)

        return filepaths

    @xml_filepaths.setter
    def something(cls, value):
        cls._something = value
```

It raises:

```python
--> 140     @xml_filepaths.setter
    141     def something(cls, value):
    142         cls._something = value

AttributeError: 'classproperty' object has no attribute 'setter'
```

As you see, the reasons seem pretty subjective, and they might be, that's why I didn't include any in the first comment :sweat_smile:

**Comment by sphuber** [comment]
The setter in your last example is wrong. The whole point of the `@property` decorator is that you do not have to change the name of the property, i.e. the setter would also be called `diameter` and not `set_diameter`.

The reason of the `classproperty` is because the builtin `classmethod` is not exactly the same, since that is a callable where the property is not. In this way, the `classproperty` for a class more closely the `property` of a class instance. This also shows why it is not really a problem that it is not completely isomorphic with the normal `property` by the `classproperty` not supporting a setter, as typically you do not want to be changing class variables like you for class *instances*.

**Comment by odarbelaeze** [comment]
> The setter in your last example is wrong. The whole point of the `@property` decorator is that you do not have to change the name of the property, i.e. the setter would also be called diameter and not set_diameter.

You're right, that's what I meant. I was a little lazy and wrote the syntax that I remembered by heart, I think that's a bad example tho, the better example might be, suppose you have a class like

```python
class Circle:
    def __init__(self, radius):
         self.radius = radius
```

and then you decide that, you'd like your circles to have only positive radii or otherwise your system will break, in python the user can access and set `circle.radius` as they please and that's how it's supposed to be, `@property` helps you enforcing this kind of logic after your `Circle` class is already in the hands of the user,

```python
class Circle:
    def __init__(self, radius):
        self.radius = radius

    @property
    def radius(self):
        return self._radius

    @radius.setter
    def radius(self, value):
        if value < 0:
            raise ValueError('We do not like negative radii')
        self._radius = value
```

Then the user can neither do `c = Circle(-3)` nor can they do:

```python
c = Circle(3)
c.radius = -3
```

Of course they can do `c._radius = -666` but since they're touching the underscored variable name, is a convention that they are on their own and they should know things may break.

> The reason of the classproperty is because the builtin classmethod is not exactly the same, since that is a callable where the property is not. In this way, the classproperty for a class more closely the property of a class instance. 

You're completely right there as well, they are not the same. The class method would require that we change the invocation to something like:

```diff
- xml_file_paths = ClassName.xml_file_paths
+ xml_file_paths = ClassName.xml_file_paths()
```

> This also shows why it is not really a problem that it is not completely isomorphic with the normal property by the classproperty not supporting a setter, as typically you do not want to be changing class variables anyway, like you for class instances.

Here I agree with you, we probably don't want people to be setting a class property, using the class property decorator if someone tried:

```python
ClassName.xml_file_paths = ['x', 'and', 'y']
```

They would get a **runtime** error saying that that particular property can't be set, if we moved to the language property `classmethod`, this is what that attempt would look like:

```python
ClassName.xml_file_paths() = ['x', 'and', 'y']
```

The syntax error they might get after that attempt may be sufficient to express that we:

> typically [...] do not want to be changing class variables anyway, like you for class instances.

This became kind of an interesting argument, I hope I'm now being rational and not lazy <3
