### ISSUE TITLE
Missing example_helpers.py causes error in test_pw.py

### ISSUE THREAD

**Issue by nathanielng** [aiidateam/aiida-quantumespresso#273]
**Script `test_pw.py` fails**

The script [`test_pw.py`](https://github.com/aiidateam/aiida-quantumespresso/blob/develop/examples/submission/quantumespresso/test_pw.py) fails on line 16:

```
$ python test_pw.py
Traceback (most recent call last):
  File "test_pw.py", line 16, in <module>
    from aiida.common.example_helpers import test_and_get_code
ImportError: No module named example_helpers
```

**Reason**

[`aiida.common`](https://github.com/aiidateam/aiida_core/tree/v1.0.0b2/aiida/common) in version `1.0.0b2` and `develop` branch does not have `example_helpers.py` (it's still there in the `master` branch, as well as the `release_v0.12.4` branch)

**Comment by sphuber** [comment]
Thanks for the report. The entire folder `examples` is outdated and will be deprecated. If you want to have a working example or simple way of launching a test `PwCalculation` use the CLI scripts in `aiida_quantumespresso/cli`. The pw one is installed as `launch_calculation_pw`

**Comment by nathanielng** [comment]
Okay, I'm running the [2019_MARVEL_Psik_MaX](https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_MARVEL_Psik_MaX/sections/calculations.html) tutorial and it seems to be working fine.  Versions: `aiida_core` v1.0.0b3 and `AiiDA-quantumespresso` v3.0.0. Will close the case when everything has been double-checked.
