### ISSUE TITLE
Homogenize exit codes across calculation classes

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#296]
One way to do it is to add the exit codes to the spec of a base class instead of individual subclasses (`NamelistsCalculation`, `BasePwCpInputGenerator`).

**Comment by sphuber** [comment]
I have started rewriting the `PwParser` to use the new exit code system and am trying to come up with a generic guideline that can also be used for other calculations. I will write the current conception and ideas here, so we can discuss it.

* `0-99` reserved for use by the `aiida-core` engine
* `100-199` unrecoverable errors, like expected output files completely missing or unexpected exceptions in raw parsing
* `200-299` potentially recoverable errors, for example part of expected output files is corrupted
* `300-399` recoverable errors: code executed nominally but there were warnings or target result not reached (e.g. not converged or not relaxed)

**Comment by ConradJohnston** [comment]
@sphuber I notice from PR #479 that there are some collisions in the exit codes still. For example, 330 is used differently by the cp, dos, projwfc, and metadyn CalcJobs classes. Was the goal here to ensure that all error codes thrown by problems that invalidate the cache have a value of less than 400, or to avoid error code collisions all together? If it's the latter, we should reopen this.

**Comment by sphuber** [comment]
There were two rules that I tried to follow in that PR:

 * The exit status integers should respect the guidelines that I set out in the post above
 * Any exit code that has the same meaning across calculation plugins should be reused as much as possible for homogeneity.

That is to say that very generic errors like `ERROR_STDOUT_MISSING` that are most likely to be applicable to multiple if not all calculations should all use the same exit code (i.e. label, exit message and exit status).

That being said, there will always be errors that are code specific. In that case it perfectly fine that the same integers have different meanings for different calculations. Note that I used the lower 300's for the most common errors and then started from 330 for more calculation specific ones. In any case, in the end it is not feasible to never reuse an integer.

Does that make sense?

**Comment by ConradJohnston** [comment]
Yes that's clear, thank you. 

On this, should the very standard exceptions, like ERROR_STDOUT_MISSING, actually be inherited from the main parent CalcJob class? This would be nice because then there could be some consistency for common errors across all plugins, not just AiiDA-QuantumESPRESSO.

**Comment by sphuber** [comment]
I would be hesitant to put this on `aiida-core` at this point, as these might make sense for most plugins that we know now, but might not in general. However, making this easier within `aiida-quantumespresso` and defining some of the generic ones on the `aiida_quantumespresso.calculations.base.CalcJob` base class, might actually be a good idea. Have to a look a bit into how that would work
