### ISSUE TITLE
List of desirable backward incompatible changes for `v3.0.0`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#304]
Since `v3.0.0` will anyway be backward incompatible, now is the time to address changes we would like to apply that would break it. Let's keep a list here to discuss:

- [ ] Remove `output_` from create links. The link type already shows they are output links so it is superfluous and leads to `node.outputs.output_parameters`
- [ ] Change the label `output_parameters` to something more applicable, maybe `results` although that might be too general
- [ ] Change output label of density of states from `Dos` to `dos` in `ProjwfcCalculation` (note that `DosCalculation` has `'output_dos'` instead)
- [x] Change input `parent_folder` to `force_constants` for `MatynCalculation`
- [ ] Change `PwCalculation` output `output_band` to `output_bands`
- [x] Change `ForceconstantsData` to `ForceConstantsData` for consistent capitalization
- [x] As above, the entry point should then become `quantumespresso.force_constants`

**Comment by giovannipizzi** [comment]
Also change the type of the ForceConstants data class to a name that is more QE-specific, leaving room in the future for a more general Force Constants Data structure? (now it only contains the raw QE files)

**Comment by sphuber** [comment]
With the entry points, that does not really matter though doesn't it? Unless you think we would need another force constants-like container in the `quantumespresso` namespace. If not, then any other plugin can use the same name, as long as it is in another namespace. Even if the class name is exactly the same, `isinstance` and the like should still work no, if they are distinct classes, just happening to have the same name. That being said, we might want to rename it from `ForceconstantsData` to `ForceConstantsData` for naming consistency, but that is not very important of course

**Comment by sphuber** [comment]
The remaining desirables will have too big an impact on existing data and code, and will require too much work for which we don't have the resources now, so I closing this. Will be releasing `v3.0.0` without the open changes
