### ISSUE TITLE
Update and move tutorial documentation

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#311]
Update (and maybe move) these 2 pages that contain tutorials on how to write a calculation plugin:
* https://aiida-core.readthedocs.io/en/stable/developer_guide/devel_tutorial/code_plugin_qe.html
* https://aiida-core.readthedocs.io/en/stable/developer_guide/devel_tutorial/code_plugin_int_sum.html

**Comment by sphuber** [comment]
I have already updated [this documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/working/calculations.html#calculation-jobs), but it is general enough that it should stay in `aiida-core`. So I think we can close this

**Comment by borellim** [comment]
I also see [this page](https://aiida.readthedocs.io/projects/aiida-core/en/latest/developer_guide/devel_tutorial/code_plugin_float_sum.html) which is potentially relevant. But I can't read all of these pages in full to check whether they are complete right now.

**Comment by sphuber** [comment]
That one also should just be updated and rewritten in `aiida-core`. Since this will apply for all plugins, not just `aiida-quantumespresso`, I wouldn't move this here. In the documentation of `aiida-quantumespresso` we should just document how to use our specific implementations

**Comment by borellim** [comment]
Sure, I agree that it should all stay in aiida-core. I was just listing another potentially relevant new page.
Thanks.
