### ISSUE TITLE
`PwBaseWorkChain`: validate the heuristics in the automatic parallelization functionality

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#328]
The heuristics that turn the analysis of an initialization `PwCalculation` into a set of resources and parallelization settings are based on an ancient benchmark set on the Dora machine of CSCS. The validity should be tested and if necessary improved.

**Comment by chrisjsewell** [comment]
FYI, I gave automatic parallelization a go (with `3dd` branch), but the workchain is failing:
The initial parallelization calculation runs fine, but then `inputs.metadata.options.withmpi` for the main calculation is being set to `False`. (Note the same calculation inputs without parallelization runs fine)

I tried changing https://github.com/aiidateam/aiida-quantumespresso/blob/615d699c6bb5de5578e96fe223f567e6d6f6f8d4/aiida_quantumespresso/workflows/pw/base.py#L280 to:

```python
self.ctx.inputs.metadata['options'] = update_mapping(options, {'resources': resources, 'withmpi': True})
```

But this didn't change anything.

The `aiida.out` content is:

```
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine mp_start_pools (1):
     invalid number of pools, out of range
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...
```

You might also consider assigning this a specific exit code in the parser, and associated error handler in the workchain.

**Comment by greschd** [comment]
Just had a look at this code, and I'm a bit confused by the following part:

```python
    # The number of nodes is the maximum number we can use that is dividing nkpoints
    num_machines = max([m for m in range(1, max_num_machines + 1) if nkpoints % m == 0])

    # If possible try to make number of kpoints even by changing the number of machines
    if (
        num_machines == 1 and nkpoints > 6 and max_num_machines > 1 and
        time_single_cpu / default_num_mpiprocs_per_machine > target_time_seconds
    ):
        num_machines = max([m for m in range(1, max_num_machines + 1) if (nkpoints + 1) % m == 0])
```

- I think the comment ``... try to make number of kpoints even ...`` doesn't really describe what's happening here. If it doesn't find a number of machines where the k-points can be distributed equally, it tries instead to distribute them _almost_ equally: such that only one machine is "missing" a k-point.
- The ``time_single_cpu / default_num_mpiprocs_per_machine > target_time_seconds`` condition is presumably to avoid wasting resources when one machine would be enough to hit the target time. But why isn't that condition also applied to the first line?

Other than that, the ``time_single_cpu`` (and, consequently, the ``scaling_law`` obtained from Dora) seems to only be used to estimate the total run time, and set the ``max_wallclock_seconds`` accordingly. As far as I can tell, this doesn't take into account different approximation levels (famously, hybrids are _much_ slower).
Is it a strict requirement that ``max_wallclock_seconds`` is calculated by this function, or could that move somewhere else / rely on user input?
