### ISSUE TITLE
Unable to import `create_builder_from_file()` (intention is to run AiiDA from existing Quantum Espresso input files)

### ISSUE THREAD

**Issue by nathanielng** [aiidateam/aiida-quantumespresso#340]
The subroutine `create_builder_from_file()` in [pwinputparser.py](https://github.com/aiidateam/aiida-quantumespresso/blob/develop/aiida_quantumespresso/tools/pwinputparser.py) cannot be imported.

```
$ verdi shell
.
.
.
In [3]: from aiida_quantumespresso.tools.pwinputparser import create_builder_from_file
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-a6d7e7f7c773> in <module>()
----> 1 from aiida_quantumespresso.tools.pwinputparser import create_builder_from_file

ImportError: cannot import name create_builder_from_file
```

**Versions**: Python 2.7.13, AiiDA 1.0.0b3, AiiDA Quantum Espresso 3.0.0a3

**Note**: The context is to run a calculation (via AiiDA) using existing Quantum Espresso input files.  The PWscf immigration route (in [this tutorial](https://aiida-quantumespresso.readthedocs.io/en/latest/user_guide/get_started/examples/pwimmigrant_tutorial.html#pwimmigrant-tutorial)) was not used in this case as the runs have yet to be made (and therefore, the Quantum Espresso output files have yet to be generated).  Currently, [pwimmigrant.py](https://github.com/aiidateam/aiida-quantumespresso/blob/develop/aiida_quantumespresso/calculations/pwimmigrant.py) applies to finished jobs (which have both Quantum Espresso input files and output files), but not to already-generated input files that have yet to be run.

**Comment by sphuber** [comment]
Where did you find the method `create_builder_from_file`? Because this was only just added yesterday in [this commit](925fef2d5bab568ffd26532ed325b58d154d34af) and so it is only in the `develop` branch and not yet released. The version of `aiida-quantumespresso` you mention therefore does not contain this utility

**Comment by nathanielng** [comment]
Apologies, it might be a mistake on my end. I'll check again.
