### ISSUE TITLE
Add 'settings' key to store kpoint files in repository when parsing bands

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#37]
In PR #36 the code was merged that deprecates the `also_bands` key in favor of always parsing the bands by default, but the k-point eigenvalue xml files that were used for the parsing are no longer stored in the repository. We should provide an optional key to switch to the old behavior to store the band files in the repository.

**Comment by mbercx** [comment]
@sphuber Just looking at some old issues, I'm wondering if this is still at all relevant. I don't even know what "the k-point eigenvalue xml files" are. ^^

**Comment by sphuber** [comment]
yeah, let's just close this. Since nobody has asked for this in 6 years, safe to say it isn't really needed.
