### ISSUE TITLE
PW Parser does not create a BandsData node among output of 'bands' calculation - pw 6.1

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida-quantumespresso#4]
I submit a `bands` calculation calculation, it runs correctly, but among the output dict I cannot not find a BandsData connected to the calculation via an output_structure link. I made sure I had `also_bands` = True` in the input settings. Ex, in verdi shell:

In [15]: calc = load_node(5258)

In [16]: calc.inp.parameters.get_dict()['CONTROL']['calculation']
Out[16]: u'bands'

In [17]: calc.inp.settings.get_dict()
Out[17]: {u'also_bands': True}

In [18]: calc.get_outputs_dict()
Out[18]: 
{u'output_array': <ArrayData: uuid: 89c67565-efb0-440a-9024-66c24b5fae6b (pk: 5262)>,
 u'output_array_5262': <ArrayData: uuid: 89c67565-efb0-440a-9024-66c24b5fae6b (pk: 5262)>,
 u'output_parameters': <ParameterData: uuid: b8c09955-de29-48ff-8df6-d103fae78d20 (pk: 5261)>,
 u'output_parameters_5261': <ParameterData: uuid: b8c09955-de29-48ff-8df6-d103fae78d20 (pk: 5261)>,
 u'remote_folder': <RemoteData: uuid: 4db83e64-891f-4e9a-8681-93479e324a2a (pk: 5259)>,
 u'remote_folder_5259': <RemoteData: uuid: 4db83e64-891f-4e9a-8681-93479e324a2a (pk: 5259)>,
 u'retrieved': <FolderData: uuid: 6bf387c6-fec3-4fa8-a67b-8dc266b5dd6b (pk: 5260)>,
 u'retrieved_5260': <FolderData: uuid: 6bf387c6-fec3-4fa8-a67b-8dc266b5dd6b (pk: 5260)>}

System Configuration:

pw 6.1
AiiDA 0.9.0,
default qe plugin (i.e. the one shipped checking out tag v0.9.0 of aiida, not the one installed with pip install aiida-quantumespresso)

**Comment by fernandogargiulo1986** [comment]
Actually, I realized that I was not necessarily running Quantum Espresso 6.1, that is, I compiled the source code cloned from the officla github mirror by pointing it to the `master` branch, whose commit does not correspond to the tag `v6.1` (v6.1 -> b490894 , master -> d985c02). It seems like `master` is being used as a `develop` branch.

The specific issue is that the `master` version creates the file `data-file-schema.xml` in folder `<outdir>/<prefix>.save` which surprisingly contains only infos of the input (it is identical to another file created by pw.x `<outdir>/<prefix>.xml`). 
AiiDA, on the other hand, expects to find output informations in the file `<outdir>/<prefix>.save/data-file.xml`, which is correctly created by a pw.x executable compiled from tag `v6.1`.  

A similar discussion applies to issue #3

**Comment by fernandogargiulo1986** [comment]
I checked that the bands are parsed correctly now and the output link 'output_band' is present.

**Comment by sphuber** [comment]
Thanks for checking this out Fernando. The change in xml files in the branch of QE that you checked out has to do with them changing the format of the xml output. We are actually working to implementing a more robust parsing of the xml file in the plugin. So as it so happens, hopefully when the next version of QE will be released the plugin will also be able to deal with those changes.

**Comment by fernandogargiulo1986** [comment]
The thing is that the current status with the xml files (master branch) looks very inconsistent (I might well be miss the underlying ratio though).  `data-file-schema.xml` is identical to <prefix>.xml and, despite its name, does not contain any schema information but only the input data. No information of the output is stored in any xml file. So, in the current state, it seems hard to make a plugin based on xml!
