### ISSUE TITLE
Bands for hybrid functionals

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#400]
For hybrid functionals, bands can not be computed in the usual manner because only self-consistent calculations are possible. They can (to the best of my knowledge) however be obtained (expensively) by explicitly specifying the k-points for SCF and adding the band k-points with weight zero.

My question is how best to integrate this procedure in the ``aiida-quantumespresso`` code. Does it make sense to have a special case in the current bands workchain, or would it be better suited for a separate workchain?

**Comment by sphuber** [comment]
I am not too familiar with hybrid functionals and how they work in Quantum ESPRESSO but if this is commonly used I would try to accomodate for it in the workchain. Unless the workflow really requires a completely different flow. Forgetting about AiiDA for a moment, what would be the manual workflow in QE for computing a band structure with HF?

**Comment by greschd** [comment]
The README in the QE EXX_EXAMPLE has this to say (emphasis mine):

>  WHAT PROPERTIES CAN I COMPUTE ?
  Energy and forces (thanks to Hellmann-Feynman theorem forces do not
  require extra calculations). In principle also stresses but the
  corresponding formulas have not yet been coded.
  So structural optimization is OK if the cell shape is kept fixed.
  **Band structure ?** yes and no. Obviously one computes wfc during the **scf**
  cycle and their **eigenvalues are printed in output**.
  This can be sufficient to draw a band structure or a DOS, but the problem
  arises when one wishes non-scf calculations in k-points different from
  those computed during the scf cycle. At present it is not possible
  because this would require the knowledge of all bands at k+q that we do
  not have. I do not know how to by-pass this problem.

This matches with my experience (using VASP), which is that eigenvalues can be obtained from the SCF calculation only -- by adding zero-weight k-points to the SCF run we can obtain more values, but typically what you can reasonably compute is a pretty sparse band structure.

Another point to consider is that AFAIK relaxation doesn't work, and it's typically a good idea to first perform a "normal" SCF calculation to improve convergence.

**Comment by greschd** [comment]
Side question: From a high-level perspective, what's the difference between the ``PwBandsWorkChain`` and ``PwBandStructureWorkChain``?

**Comment by sphuber** [comment]
The `PwBandsWorkChain` is the "dumb" one, as in it encodes the workflow logic, but it is up to the caller to correctly define the inputs. The `PwBandStructureWorkChain` is a first proof of principle of a "turn-key" solution. All it does then is for some minimal inputs (structure, code and protocol) determine the full set of inputs and then simply calls `PwBandsWorkChain`.

**Comment by sphuber** [comment]
So if I understand correctly, computing a band structure with hybrid amounts to optionally doing a relax at fixed-cell followed by an SCF. The resulting bands is the best you can do. So basically running the NSCF as we do currently in the `PwBandsWorkChain` is not useful? Is that correct?

**Comment by greschd** [comment]
I think it would be an optional relax and SCF _without hybrids_, followed by an SCF with added zero-weight k-points, with hybrids.

Running the NSCF would be useful, but it's not possible (which amounts to the same, really).

**Comment by greschd** [comment]
Maybe it makes sense for me to work on this as a separate workflow to start, and then we can decide how / if it should be integrated. Since they're pretty different overall, it might just amount to being a top-level switch when hybrids are enabled.

**Comment by sphuber** [comment]
Of course if you are willing to have a look what the workchain would look like, if it won't make the logic of the existing ones super complicated, I think it would be nice to have them integrated.

**Comment by greschd** [comment]
I'll start by experimenting with a separate workchain, once I have a better understanding of the logic required it will be easier to judge if they can go together.

You can assign the issue to me.

**Comment by greschd** [comment]
It turns out this way of calculating bands doesn't work in QE, unless the ``nqx`` are set to 1. Since that doesn't make too much sense (the results might not be converged), I think we can close this issue for now.
