### ISSUE TITLE
Promote parallelization settings to "proper" inputs?

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#405]
As far as I can tell, the parallelization options can currently only be specified using the ``settings.cmdline`` option.

To make this a bit more accessible, maybe it would make sense to instead specify them as "real" inputs, with their own input ports? This could also allow for some validation, e.g. that the options are compatible with the number of cores.

Related issue: #328.

**Comment by sphuber** [comment]
Are you proposing an input port on the `PwCalculation` class. For example a `Dict` node with the keys:
* `ni`
* `nk`
* `nt`
* `nd`
which correspond to the available parallelization flags.
We are currently working with @zooks97 on understanding the parallelization options in Quantum ESPRESSO and how we can automate the selection of them.

**Comment by greschd** [comment]
Yeah, something like that. I think this would be pretty independent of the automated parallelization, except for changing how the parameters are passed to the ``PwCalculation``.

I'm not sure if the "long" version of the flags  (``nimage``, ``npools``, ``nband`` ``ntg`` ``ndiag``) would be easier to use, or if both should be allowed.

**Comment by sphuber** [comment]
No you are right, I think we should stick with the longer versions and only those. There being multiple version on QE itself is already confusing enough.

**Comment by greschd** [comment]
Maybe it would be more appropriate to make it an input namespace, with each value set as an ``Int``? 
That way we wouldn't have to handle the default case in code, but you could still specify only one of the parameters with the others having the default.

Not handling the default in code also has benefits for caching, because no input and input=1 are actually the same.

**Comment by greschd** [comment]
We should probably have a chat about parallelization options @zooks97 @sphuber. I'm currently running some tests, but my understanding is pretty limited still.

**Comment by greschd** [comment]
@sphuber this seems relatively straightforward, I can have a crack at adding it. A few questions about how you want the interface to look:
- Should the parallelization inputs be a single ``Dict``, or would you prefer the namespace approach described above?
- If the parallelization options are also given in the ``CMDLINE`` argument, what should happen? Can we just raise ``InputValidationError``, or should we somehow preserve backwards compatibility by merging the options?

**Comment by greschd** [comment]
Ping @sphuber on the design questions above.

**Comment by greschd** [comment]
Another question: As far as I understand, different codes can have the same parallelization flags, but they are not _necessarily_ implemented.

How should we handle this? Implement them at the `BasePwCpInputGenerator` but then have a list of "allowed" parallelization flags per calculation class?

**Comment by greschd** [comment]
See the draft PR #554 - added just because it's easier to talk about things when there is actual code.
