### ISSUE TITLE
Possibility for explicit "nbnds" in "PwBandsWorkChain"?

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#441]
When calculating a band structure for comparison with a known reference, I sometimes want to explicitly specify ``nbnd`` for the bands step in ``PwBandsWorkChain``. Currently, ``nbnd`` in the ``bands`` step is calculated via ``nbands_factor`` - to explicitly set ``nbnd``, the factor has to be "reverse-engineered".

An alternative would be to make ``nbnds_factor`` optional, and use it only when there is no ``nbnd`` set in the ``bands.pw.parameters`` input. I'm not sure if that's a common enough use case, though. @sphuber, thoughts?

**Comment by sphuber** [comment]
I would be fully on-board with this change actually as I didn't design it in this way originally but others put it in. My original idea for the `PwBandsWorkChain` (as well as the `PwRelaxWorkChain` and the `PwBaseWorkChain`) is to make it as generic as possible and by using the expose functionality leave all options open to the user. It is not intended to be a "turn-key" solution by automatically choosing inputs, that is up to the caller. So I think the behavior should be that `nbands_factor` is completely optional and is only used when specified. A caller can then omit it and specify directly through the pw parameters

**Comment by greschd** [comment]
Ok, should be simple enough to change. For the validation, we just pass a ``validator`` in ``namespace_options`` when exposing, right?
