### ISSUE TITLE
parse xml dynmat files for ph calculation

### ISSUE THREAD

**Issue by tsohier** [aiidateam/aiida-quantumespresso#442]
Currently the ph parser fails if the dynamical matrix file is in the xml format. This is necessary to run ph calculations on systems with SOC. It used to work at some point, could it come back?

**Comment by sphuber** [comment]
Under which conditions is the dynamical matrix file in XML? And could you maybe provide an example calculation with those outputs such that we can write a test for it?

**Comment by tsohier** [comment]
The case I'm currently interested in is if you use SOC in your calculation: in practice, when the parent pw calculation was run with :

parameters['SYSTEM']['noncolin'] =  True
parameters['SYSTEM']['lspinorb'] = True

and relativistic pseudos.

I think there are other cases when it happens: when you parallelize on modes maybe, and potentially others. Anyway, I believe it will be the default format in the future, so, it's good to deal with it. 

For an example, you could maybe run anything you already have but with relativistic pseudos and the above option for the pw input?

**Comment by sphuber** [comment]
I cannot reproduce this, the files in `DYNMAT` are always plain text. I ran with QE 6.4.1 a pw.x calculation with the flags you specified and a relativistic pseudo. Then I launched a ph.x calculation on the results but dynmat files are not in XML format. Is there something I am missing?

**Comment by sphuber** [comment]
Also, I tried to find where in the old code it was parsing XML variants of the dynamical matrix output and I cannot find it. In the latest stable release v2.1.0 the [raw parser](https://github.com/aiidateam/aiida-quantumespresso/blob/f45ae51ab6f0c7236237ffd993d81c87bbb36e05/aiida_quantumespresso/parsers/raw_parser_ph.py#L14) only ever reads the plain text variants. So in which version was this working? Do you know which version of `aiida-quantumespresso` this was being parsed?

**Comment by tsohier** [comment]
Ok, this is because I have an older QE version. The issue is irrelevant now, as they went back to plain text as the default format. See https://gitlab.com/QEF/q-e/issues/38.

Sorry to have bothered you with this, I'll deal with this on my side. Thanks!
