### ISSUE TITLE
`PwParser`: incorrectly assumes calculations to not be converged for external pressures

### ISSUE THREAD

**Issue by JPchico** [aiidateam/aiida-quantumespresso#449]
Dear AiiDa Team

I'm currently writing a workflow which makes use of the `PwRelaxWorkChain` workchain. I have done this in a Ubuntu18.04 machine with the following AiiDA version:

-  aiida-core:  v1.0.1 hash: e74ad1b36
-  aiida-quantumespresso: v3.0.0a5 hash: 6ef6af1

The volume relaxations are performed at fixed pressure (`press` keyword), making use of the `vc-relax`. The calculations go as one would expect with several bsgf steps being performed until convergence is reached. However, `PwRelaxWorkChain` reports the calculation as failed with exit code 500, `The ionic minimization cycle did not converge for the given thresholds.`.

I have noticed that this issue seems to be related to the verify_convergence_stress function found in `aiida-quantumespresso/aiida_quantumespresso/utils/validation/trajectory.py`.

This function checks 
```
(numpy.trace(stress) / 3.) < threshold
```
which is fine if there is no external pressure. However, as soon as an external pressure is applied this condition cannot be fulfilled, as the stress tensor would be shifted by the applied pressure. This becomes more apparent when one applies a negative pressure,  where the offset results in the condition being always fulfilled. 

Thus I guess that one should change the function to something akin to
```
numpy.abs(numpy.trace(stress)/3. - ext_pressure) < threshold
```

**Comment by sphuber** [comment]
Thanks for the report, this is indeed a bug. I had to add manual checks for convergence as there are modes where QE reports the structure as converged when in fact it isn't. I didn't take your use case into account. Can you tell me where exactly you specify the pressure? Is this in the parameters input node?

**Comment by JPchico** [comment]
@sphuber Thanks for your quick reply. Yes I specify it in the input parameters of the code. I add an entry to the parameters dictionary like the following
```
parameters = {
    'CELL': {
        'press': val_pressure
     }
......
}
```

**Comment by sphuber** [comment]
I have personally never run relax calculations with external pressure. Should the cell stress be completely ignored in this case during the relaxation? So we just double check that the forces on the atoms are below the specified threshold? Would that be the correct behavior?

**Comment by JPchico** [comment]
I think so. I'm also quite new to external pressure calculations, but if you are alloying a full cell relaxation (all lattice vectors can vary) the average of the diagonal of the stress tensor should correspond to the target pressure. 

So what I guess is necessary is to see if the positions of the atoms are indeed below the specified threshold and if the average of the trace corresponds to the external pressure between the specified threshold.

**Comment by giovannipizzi** [comment]
> Should the cell stress be completely ignored in this case during the relaxation?

No, I think we should do the check suggested by @JPchico `numpy.abs(numpy.trace(stress)/3. - ext_pressure) < threshold` (with default `ext_pressure` being zero if not specified in input - BTW, I'm pretty sure this should be parsed.

**Comment by JPchico** [comment]
Thanks for your input @giovannipizzi ! I have been looking more into this, as the pressure is passed in the `parameters: {'CELL':}` entry I guess it should be possible to do something like what is done for the other quantities
```
threshold_stress = parameters.get('CELL', {}).get('press_conv_thr', pw.press_conv_thr)
```
something like
```
threshold_pressure = parameters.get('CELL', {}).get('press', pw.press)
```
then one could pass it by the `thresholds` variable by something like
```
thresholds = [threshold_forces, threshold_stress,threshold_pressure]
```
Then it would be a manner of changing the check as suggested. I could try to hack it in my aiida-quantumespresso installation and see if this solves the issue.

**Comment by JPchico** [comment]
I was looking more closely at this, and I think that the  `XMLParser` does get the information about the pressure, which can be accessed by 
```
xml_dictionary['input']['cell_control']['pressure']
```
However, this is not passed to the `parameters` dictionary as it is not contained in the `xml_data` dictionary. 
What I did then was to add the  `pressure` key in the `xml_data` dictionary and use the proposed fix.

The test I have performed seem to pass, so perhaps this is the easiest way to address this issue.

**Comment by JPchico** [comment]
@sphuber I think I have managed to solve the issue, I have tested my implementation with several versions of QE (5.4, 6.1.0, 6.2.0, 6.3 and 6.4.1) 

The "fix" seems to work, basically it takes the `press` value that is stored in the input values and if this value exists is then attached to the `parsed_parameters` dictionary

```
        parameters = self.node.inputs.parameters.get_dict()

        parsed_xml, logs_xml = self.parse_xml(dir_with_bands, parser_options)
        parsed_stdout, logs_stdout = self.parse_stdout(parameters, parser_options, parsed_xml)

        parsed_bands = parsed_stdout.pop('bands', {})
        parsed_structure = parsed_stdout.pop('structure', {})
        parsed_trajectory = parsed_stdout.pop('trajectory', {})
        parsed_parameters = self.build_output_parameters(parsed_stdout, parsed_xml)

        try:
            parsed_parameters['pressure'] = parameters['CELL']['press']*0.10
        except KeyError:
            parsed_parameters['pressure'] = 0.0
```
which then is passed to the `verify_convergence_trajectory` function.

If you think this a good solution, I could make a pull request about this.
