### ISSUE TITLE
Set "invalidates_cache" exit code keyword where appropriate

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#452]
Since we implemented the "invalidates_cache" keyword on "exit_codes", I think it makes sense to use this here where appropriate.

@sphuber, do you think the 300's exit codes should have that flag? Or only some of them?

An important consideration is that the plugin should still work if the functionality is not present. I think a good way to do this would be something like
```python
if 'invalidates_cache' in ExitCode._fields:
    INVALIDATES_CACHE_INPUT = {'invalidates_cache': True}
else:
    INVALIDATES_CACHE_INPUT = {}
```
and then pass ``**INVALIDATES_CACHE_INPUT``. Where's a good place to put this code? Do we have a compatibility helper module somewhere?

**Comment by sphuber** [comment]
Not sure where you imagine putting this code?

**Comment by greschd** [comment]
Some utility module, I guess? Is ``utils`` the right place for this kind of helper?

**Comment by greschd** [comment]
And then setting the flag in the various ``define`` methods, of course.

**Comment by sphuber** [comment]
I agree that we should add `invalidates_cache=True` to all `300` exit codes, however, I still do not understand where you want to pass `**INVALIDATES_CACHE_INPUT`. Do you mean somewhere in the restart workchain? I am not sure what you mean with:
> plugin should still work if the functionality is not present'

**Comment by greschd** [comment]
Ah, now I understand your question 😄

Since the functionality for ``invalidates_cache=True`` was implemented after AiiDA 1.0, simply passing ``invalidates_cache=True`` to the ``spec.exit_code`` would break 1.0 compatibility. By creating this dictionary (which would be empty on 1.0) and passing it as
```
spec.exit_code(..., **INVALIDATES_CACHE_INPUT)
```
we pass ``invalidates_cache=True`` or _nothing_, depending on the AiiDA version.

**Comment by sphuber** [comment]
> Ah, now I understand your question smile

Ah, now I understand your suggestion :smile: 
We could do this for compatibility, but there are most likely going to be multiple changes that depend on changes that will only be in `aiida-core==1.1` so maybe we can just require `aiida-core>=1.1` when we release `aiida-quantumespresso==3.0.0`. Only problem, now that I think about it, is that I planned on having `3.0.0` to be a python 2 compatible version for `aiida-core>=1`, but since `1.1` dropped py2 support that would not be possible.

**Comment by greschd** [comment]
Yeah, I think that's a reasonable way of doing it. As long as there's a comment containing the string ``python2`` nearby we ought to not forget about it upon moving to py3 only.
