### ISSUE TITLE
`PpCalculation` also needs to copy `pseudo` folder

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#461]
This is required for certain post-processing modes but is currently not added to the `remote_copy_list`

**Comment by greschd** [comment]
Ah, because I couldn't reproduce the issue I reported in #428 (with non-stupid inputs) I somehow assumed this wasn't needed.
Just out of curiosity, do you know which kind of post-processing actually uses the pseudos?
