### ISSUE TITLE
Bug in  pw base workflow

### ISSUE THREAD

**Issue by mikeatm** [aiidateam/aiida-quantumespresso#47]
The spec expects `ParameterData`  [here](https://github.com/aiidateam/aiida-quantumespresso/blob/develop/aiida_quantumespresso/workflows/pw/base.py#L62) but then uses it as a dictionary  in these lines [here](https://github.com/aiidateam/aiida-quantumespresso/blob/develop/aiida_quantumespresso/workflows/pw/base.py#L140,L142) ,  
 `ParameterData` does not offer the  `.get`  method.

**Comment by sphuber** [comment]
Good catch Mike, this is a bug that I accidentally introduced when implementing the `automatic_parallelization`. I will submit a PR to fix it. Thanks!
