### ISSUE TITLE
consider pointing AiiDA registry to other branch

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-quantumespresso#480]
The AiiDA registry points to the master branch and so is still looking at the aiida-qe plugin for AiiDA 0.12.
https://aiidateam.github.io/aiida-registry/

I suggest you either point the registry to the development branch for the time being, or you merge the last alpha release into the master branch (it should anyhow be more useful than the current state of the master branch).

**Comment by sphuber** [comment]
Thanks @ltalirz good point. I am focusing on the `aiida-quantumespresso` plugin package this week and the next in order to release `3.0.0`. Once released this will be merged into master and so will address this question.

**Comment by sphuber** [comment]
v3.0.0 has now been released: https://pypi.org/project/aiida-quantumespresso/
