### ISSUE TITLE
AiiDA plugins' co-operating capability on input files for different DFT codes within the workflow

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/aiida-quantumespresso#481]
Hi,

See my suggestion here:
https://github.com/aiida-vasp/aiida-vasp/issues/318

What do you think about it?

Regards

**Comment by sphuber** [comment]
Hi @hongyi-zhao . This is an interesting suggestion indeed, and one we have already been discussing ourselves. Particularly, very recently at the [AiiDA hackathon at CINECA](https://events.prace-ri.eu/event/957/overview) in Bologna, Italy. You can find a [report of this discussion online](http://www.aiida.net/wp-content/uploads/2020/02/Bologna-hackathon-report.pdf). The relevant section is the first section on page 2-4. As a result of these initial discussions, we have created a new repository [`aiida-common-workflows`](https://github.com/aiidateam/aiida-common-workflows) where we are building these common interfaces for various DFT codes. We will at the very least attempt to implement this for Quantum ESPRESSO, VASP and SIESTA. We can continue this discussion there and you are free to join and follow the progress of course.

**Comment by sphuber** [comment]
I am closing this and discussion should continue in the linked repository
