### ISSUE TITLE
Some outdated usage still in tutorial.

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/aiida-quantumespresso#504]
Hi,

See [here](https://aiida-quantumespresso.readthedocs.io/en/latest/user_guide/get_started/examples/ph_tutorial.html)

Some outdated usages still appeared there, say the following: 

 ` from aiida import load_dbenv ` should be: `from aiida import load_profile `

 `calc = code.new_calc()` should be: `calc = code.get_builder()`

and

```
calc.set_option('max_wallclock_seconds', 30*60) # 30 min
calc.set_option('resources', {"num_machines": 1})
calc.use_parameters(parameters)
```

Should be:
```

 calc.metadata.options= {
     "max_wallclock_seconds": 30*60,  # 30 min
     "resources": {
         "num_machines": 1
     }
 }
```

Regards

**Comment by sphuber** [comment]
Thanks for the report, but there is no need to report these. We are aware that the documentation is outdated and we hope to fix it as soon as possible
