### ISSUE TITLE
Problem with the XSD of QE

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-quantumespresso#553]
The [XSD (XML schema)](https://github.com/aiidateam/aiida-quantumespresso/blob/61fe3b4ec0b90df4dbc5dad7c452b47b83eef071/aiida_quantumespresso/parsers/parse_xml/pw/schemas/qes_191206.xsd) that is currently in the code has a problem when the functional is not provided all upper case.

E.g., if I specify `input_dft = 'rvv10'` (lower case), then In the output XML only one of the two values is converted to upper case:
```
$ verdi calcjob outputcat 2273 data-file-schema.xml | grep -i rvv10 
      <functional>rvv10</functional>
      <functional>RVV10</functional>
```

And then the parser fails with this error:
```
 | failed validating 'rvv10' with XsdEnumerationFacets("['PZ', 'BP', 'PBE', 'REVPBE', 'PBESOL', ...]"):
 | 
 | Reason: invalid value 'rvv10', it must be one of ['PZ', 'BP', 'PBE', 'REVPBE', 'PBESOL', 'BLYP', 'OLYP', 'PW91', 'WC', 'SOGGA', 'EV93', 'B3LYP', 'GauPBE', 'PBE0', 'HSE', 'VDW-DF', 'VDW-DF-CX', 'VDW-DF-C09', 'VDW-DF-OB86', 'VDW-DF-OBK8', 'VDW-DF2', 'VDW-DF2-C09', 'VDW-DF2-B86R', 'RVV10']
 | 
 | Schema:
 | 
 |   <enumeration xmlns="http://www.w3.org/2001/XMLSchema" value="PZ" />
 | 
 | Instance:
 | 
 |   <functional>rvv10</functional>
 | 
 | Path: /{http://www.quantum-espresso.org/ns/qes/qes-1.0}espresso/input/dft/functional
```

[This file](https://github.com/QEF/qeschemas/blob/912e059ae52c076616f132367b763fa0741a3fc7/PW_CPV/qes_devel_030920.xsd) fixes the capitalisation issue

Should we just overwrite the XSD version 191206 that is in the repo? This file is picked when parsing the output , since the XSD version is written by QE in the output of each run.
And how do we keep track of the 'version' of the patch fix of the XSD? Pinging @sphuber and @mbercx  for comments

**Comment by sphuber** [comment]
If the patched XSD is compatible with all potential output files that would have been compatible with the 191206 version, then overwriting would in principle be better. However, if the patch version is based on a new version that introduces other changes, then that wouldn't necessarily work. Currently, we have never had to deal with patch versions of the XSD and simply used entire new versions.

**Comment by giovannipizzi** [comment]
I'll check if the only changes are these, and replace the file
