### ISSUE TITLE
Parsing Electronic and Ionic Dipole in pw calculations with applied external electric field

### ISSUE THREAD

**Issue by ChRicca** [aiidateam/aiida-quantumespresso#56]
When performing a pw calculation in presence of an applied external electric field, the electronic and ionic dipoles are printed in pw.out for every iteration of the scf procedure.  See PW/examples/example10:

pw.in
```
&control
    calculation='scf'
    restart_mode='from_scratch',
    prefix='silicon',
    lelfield=.true.,
    nberrycyc=3
    pseudo_dir='$PSEUDO_DIR/',
    outdir='$TMP_DIR/'

 /
 &system
    ibrav= 1, celldm(1)=10.18, nat=  8, ntyp= 1,
    ecutwfc = 20.0
 /
 &electrons
    diagonalization='david',
    conv_thr =  1.0d-8,
    mixing_beta = 0.5,
    startingwfc='random',
    efield_cart(1)=0.d0,efield_cart(2)=0.d0,efield_cart(3)=0.001d0
```
pw.out
```
Electronic Dipole per cell (a.u.)  0.926395840102385
Ionic Dipole per cell (a.u.)   115.173552519665
Electronic Dipole on Carthesian axes
           1 -1.208125742863772E-005
           2 -4.814216075399945E-006
           3  0.926395840102385
Ionic Dipole on Carthesian axes
           1   115.173552519665
           2   115.173552519665
           3   115.173552519665
```
I would need these quantities to be parsed by AiiDA (and ideally to be returned also in the output_parameters of the PwBaseWorkChain)

**Comment by sphuber** [comment]
Would you need the averaged values, or the projected values along each cartesian axis?

**Comment by ChRicca** [comment]
Would it be possible to have both?

**Comment by sphuber** [comment]
Everything is possible :) I will look into it

**Comment by ChRicca** [comment]
In case the calculation type is "relax", would it be possible to have the averaged ionic and electronic dipoles parsed both after the first scf and after the last one for the fully relaxed structure?

**Comment by sphuber** [comment]
I just ran an example calculation to get a sample of the output and I find the following at the end of each iteration in the SCF cycle:

```
     Expectation value of exp(iGx): ( 0.19023741329127966     , -2.9365288451890961E-003)  0.99999999999999989     
     Electronic Dipole per cell (Ry a.u.)  -5.0414176187580692E-002
     Ionic Dipole per cell (Ry a.u.)   14.511546451796718     

     Expectation value of exp(iGx): ( 0.19025937843838486     ,  3.2530108401786469E-003)  0.99999999999999989     
     Electronic Dipole per cell (Ry a.u.)   5.5840069281927390E-002
     Ionic Dipole per cell (Ry a.u.)   14.511546451796718     

     Expectation value of exp(iGx): ( 0.19023459740275078     ,  2.8137152432366076E-003)  0.99999999999999989     
     Electronic Dipole per cell (Ry a.u.)   4.8306747663867958E-002
     Ionic Dipole per cell (Ry a.u.)   14.511546451796718     
Electronic Dipole on Cartesian axes
           1   3.8366858010058097E-003
           2  -1.4901769999832309E-003
           3   7.3642920501365935E-002
Ionic Dipole on Cartesian axes
           1   14.511546451796718     
           2   14.511546451796718     
           3   14.511546451796718
```

I am not sure why the lines for the electronic and ionic dipole per cell occur three times. They seem identical. Which ones need to be parsed? All of them? And do you need the values of every cycle, or just those of the last iteration. Parsing all of it feels a bit unnecessary (at least by default) and will cost a lot of unnecessary space.

And so for "trajectory runs", i.e. `relax` or `md`, it would have to parse the values from the last iteration in the SCF in the first and final relax iteration?

**Comment by ChRicca** [comment]
You would need to parse only the last (third) occurrence, only for the last iteration of the scf procedure.
 
For trajectory runs, it should have to parse these values from the last scf iteration of the first and final relaxation steps.
