### ISSUE TITLE
Add nightly build that runs the test suite of `develop` against the `develop` branch of `aiida-core`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#567]
This will give us a chance to catch breaking changes in `aiida-core`. Ideally, we would be able to run it against the latest release of `aiida-quantumespresso` as well, although this might become more tricky. If, for example, `aiida-core/develop` is updated to become the next major release, e.g. v2.0.0, the last stable release _will_ most likely fail, but that is expected. Getting failing builds in this case will be false positives.

**Comment by greschd** [comment]
> Getting failing builds in this case will be false positives.

I'd say it's still worth it to enable these tests. If it starts failing due to a version incompatibility, we probably know about the reason and can disable them temporarily.
