### ISSUE TITLE
Switch job submission cmdline arg from `<` to `-in`

### ISSUE THREAD

**Issue by qiaojunfeng** [aiidateam/aiida-quantumespresso#586]
I noticed QE (maybe only for newer version) generates an `input_tmp.in` file if using `<` for job submission, e.g. `mpirun ... pw.x ... < aiida.in`. Use `mpirun ... pw.x ... -in aiida.in` could get rid of this file. 

The `BasePwCpInputGenerator` already does this
https://github.com/aiidateam/aiida-quantumespresso/blob/0db79787b7537a261d79d2a5e22f15f7e5f4c789/aiida_quantumespresso/calculations/__init__.py#L204-L214

But this is not done for `ProjwfcCalculation`, `Pw2wannier90Calculation`, etc.
I override the `prepare_for_submission` method of `NamelistsCalculation` like this
https://github.com/qiaojunfeng/aiida-quantumespresso/blob/affa15cceda3f776f5884b9b1ca3e0f8b23ab66b/aiida_quantumespresso/calculations/pw2wannier90.py#L63-L71

But this needs to be applied to both `ProjwfcCalculation`, `Pw2wannier90Calculation`, etc. Should we directly do this in `NamelistsCalculation`?

**Comment by greschd** [comment]
> maybe only for newer version

I think that's an important question: If it's only for newer versions, when did it start being supported?

**Comment by sphuber** [comment]
I think the major reason for using `-in` instead of normal stdin redirection using `<` is that the latter is not really reliable when using MPI. The `-in` argument is defined by `pw.x` and guarantees that all procs will read the correct input.

Is the generation of the `input_tmp.in` a problem @qiaojunfeng ? It doesn't really hurt does it? It won't get retrieved by the plugin and at some point the scratch is cleaned anyway

**Comment by greschd** [comment]
I think @qiaojunfeng proposes consistently replacing `<` with `-in`, not the other way around.

**Comment by sphuber** [comment]
> I think @qiaojunfeng proposes consistently replacing `<` with `-in`, not the other way around.

Yeah, that much I understood, and I don't think it is a bad choice, if all other binaries also support the `-in` flag. Just wondering what the problem was with the generated input file

**Comment by qiaojunfeng** [comment]
> I think the major reason for using `-in` instead of normal stdin redirection using `<` is that the latter is not really reliable when using MPI. The `-in` argument is defined by `pw.x` and guarantees that all procs will read the correct input.

Yes you are right, MPI is the reason. I was setting up a new slurm configuration together with Intel MPI, but `pw.x` was not running parallelly. Initially I suspected `<` was not working correctly with my slurm and Intel MPI, but finally, I found the problem was not caused by `<`. In principle the `-in` is more stable than `<` so I thought maybe we could switch to `-in`. But anyway, I haven't found a case that `-in` works but `<` doesn't.

> Is the generation of the `input_tmp.in` a problem @qiaojunfeng ? It doesn't really hurt does it? It won't get retrieved by the plugin and at some point the scratch is cleaned anyway

No, `input_tmp.in` does not hurt. I just think it's cleaner to git rid of it 😂

Thanks guys, this is not a real problem, both `<` and `-in` works well!

**Comment by sphuber** [comment]
So can this be closed?
