### ISSUE TITLE
`iverbosity` is not working in ph.x 6.6 anymore

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-quantumespresso#606]
running `ph.x` 6.6 raising the following error:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine  read_namelists (1):
      bad line in namelist &inputph: "/" (error could be in the previous line)
``` 
change iverbosity to `verbosity = 'default'` fix this issue.

-----------
aiida-quantumespresso version is 3.2.1

**Comment by sphuber** [comment]
Thanks @unkcpz , could you provide the input file written by the plugin that caused this error, i.e. `verdi calcjob inputcat PK`

**Comment by unkcpz** [comment]
```
&INPUTPH
  epsil = .false.
  fildyn = 'DYN_MAT/dynamical-matrix-'
  iverbosity = 1
  ldisp = .false.
  max_seconds =   1.7100000000d+03
  outdir = './out/'
  prefix = 'aiida'
  recover = .true.
  tr2_ph =   1.0000000000d-16
/
      0.3535533906       0.3535533906       0.3535533906
```
Here is the `aiida.in` of the calculation which on top of the silicon scf calculation.

**Comment by unkcpz** [comment]
@sphuber I think it is this commit https://gitlab.com/QEF/q-e/-/commit/0c450d31f5e404e05e0704ac8c42c7c569064764 that function  `check_namelist_read` makes the `iverbosity` failed. 

tagging @sponce24  for inputs.
