### ISSUE TITLE
project.x cannot find data-file-schema.xml

### ISSUE THREAD

**Issue by hezhengda** [aiidateam/aiida-quantumespresso#610]
The version of the codes:
* aiida-core: v1.5.0
* aiida-quantumespresso: v3.2.1

I'm trying to use aiida-quantumespresso to calculate the PDOS (by using projwfc.x).

In my pw.x calculation, the structure of out foler is: ~/out/aiida.save/data-file-schema.xml

But when aiida copied the files to projwfc.x folder, the structure of the out folder is: ~/out/data-file-schema.xml.

So that the projwfc.x cannot read data-file-schema.xml because there is no aiida.save, hence it appears an error: "fatal error reading xml file".

Is there any quick solution for this issue?

Thanks!

Best,
Zhengda

**Comment by sphuber** [comment]
What are you passing as input for the `parent_folder` to the `ProjwfcCalculation`? You should probably pass the `remote_folder` of the `PwCalculation`. Are you perhaps passing the `retrieved` one instead?

**Comment by hezhengda** [comment]
That's indeed a lot simpler, Thanks!
