### ISSUE TITLE
parser for pw.x cannot get two Fermi energies (for spin up&down)

### ISSUE THREAD

**Issue by hezhengda** [aiidateam/aiida-quantumespresso#621]
Dear aiida-quantumespresso developers,

I'm doing spin-polarized simulation, and in the output file (aiida.out), there are two fermi energies:

`the spin up/dw Fermi energies are    11.1196    7.8565 ev`

But when I check the node.res data, I can only find the parameter `fermi_energy_units`, but no fermi energy.

I'm guessing the parser can only get 1 value for Fermi energy? I may be wrong.

Best,
ZDH

**Comment by hezhengda** [comment]
Dear developers,

I looked into the parser document `aiida-quantumespresso/aiida_quantumespresso/parsers/parse_raw/pw.y`.

In line 739-745 the code is:

```
            elif 'the Fermi energy is' in line:
                try:
                    value = float(line.split('is')[1].split('ev')[0])
                    trajectory_data.setdefault('fermi_energy', []).append(value)
                    parsed_data['fermi_energy' + units_suffix] = default_energy_units
                except Exception:
                    logs.warning.append('Error while parsing Fermi energy from the output file.')
```

But when we have spin-polarzation calculation, the output regarding to Fermi energies would be:

`the spin up/dw Fermi energies are     6.0941    5.5202 ev`

so the parser needs to add another condition, my suggestion is in the following:

```
            elif 'Fermi energies are' in line:
                try:
                    value = line.split('are')[1].split('ev')[0].split()
                    value = [float(e) for e in value]
                    trajectory_data.setdefault('fermi_energy', []).extend(value)
                    parsed_data['fermi_energy' + units_suffix] = default_energy_units
                except Exception:
                    logs.warning.append('Error while parsing Fermi energy from the output file.')
```

**Comment by mbercx** [comment]
Hi @hezhengda, thanks for reporting! I've opened #622 to implement your suggestion with some minor changes and a test. There are still some open questions there, feel free to add your input.
