### ISSUE TITLE
Rename `RelaxType.ATOMS` to `RelaxType.POSITIONS`

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#657]
Because the `RelaxType` enum replaces `ATOMS` by `POSITIONS` in [this](https://github.com/aiidateam/aiida-common-workflows/commit/67f2e39773bbe250152dd6997af3e6d2f7f21dd1) `aiida-common-workflows` commit, an error is currently raised when trying to run any of the common work chains with these relax types. So we'll have to similarly adapt the `RelaxType` enum here.

Thanks to @yakutovicha for reporting this issue!

**Comment by sphuber** [comment]
just making a note here that we will also have to make a new patch release and update the minimum required version of `aiida-quantumespresso` in `aiida-common-workflows`.

**Comment by mbercx** [comment]
Fixed by #658
