### ISSUE TITLE
`PwBandStructureWorkChain`: Deprecate and fix issues

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#687]
The `PwBandStructureWorkChain` is a legacy version of a band structure work chain with a pre-defined protocol, mostly used for previous tutorials. However, now that the `PwBandsWorkChain` has been equipped with a protocol through the `get_builder_from_protocol()` method, it no longer serves a purpose and should be deprecated.

However, we should still introduce a fix for the issues people have been experiencing when trying to run this work chain, so it's still functional until v4.0.0 is released and the work chain is removed. Two issues reported so far:

* No support for `aiida-pseudo` pseudos.
* An issue @atztogo ran into recently related to the `calculation` tag being missing:

```Python
 File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/plumpy/process_states.py",
line 230, in execute
   result = self.run_fn(*self.args, **self.kwargs)
 File "/home/max/codes/aiida-core/aiida/engine/processes/workchains/workchain.py",
line 214, in _do_step
   finished, stepper_result = self._stepper.step()
 File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py",
line 299, in step
   finished, result = self._child_stepper.step()
 File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py",
line 250, in step
   return True, self._fn(self._workchain)
 File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_quantumespresso/workflows/pw/relax.py",
line 362, in results
   if self.inputs.base.pw.parameters['CONTROL']['calculation'] != 'scf':
KeyError: 'calculation'
```

**Comment by mbercx** [comment]
Thanks again @atztogo for reporting!

**Comment by atztogo** [comment]
Thanks @mbercx and @sphuber.
