### ISSUE TITLE
Allowing electronic non-convergence if `electron_maxstep = 0` in `PwCalculation`

### ISSUE THREAD

**Issue by zooks97** [aiidateam/aiida-quantumespresso#694]
To start, a quote from Paolo Giannozzi:

> QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.

For my research, I've ended up hacking `pw.x` so that it handles the following input better:
```
&CONTROL
    calculation = 'scf'
/
&ELECTRONS
    electron_maxstep = 0
    scf_must_converge = .false.
/
...
```

In current versions, this input will lead to the Fermi level and occupations not being written out to `data-file-schema.xml`, but in my hacked version it does write these.

Soo.... I can use `dos.x` for Fermi-centered DOS 😄 .

However, `aiida-quantumespresso`, ever vigilant, still finds the pesky `convergence NOT achieved` in the output and the PWscf parser returns a `401`, which causes the `PwBaseWorkChain` and eventually the `PdosWorkChain` to pull the fire alarm.

I propose to put a check in the PWscf parser so that if `electron_maxstep == 0` or `not scf_must_converge`, the `401` exit status is not returned.

I'm not sure if this would cause any unintended side effects (nausea, vomiting, diarrhea, etc.), so I'd be happy to hear any feedback before I do a tiny PR.

**Comment by sphuber** [comment]
One solution would of course be to ignore the `convergence NOT achieved` if these settings are present in the output and simply return `0` as the exit status. However, that might give problems if there are workflows that assume `0` really means converged. Instead, I would propose to dedicate a non-zero exit status to this use case and the `PwBaseWorkChain` can then add a process handler that treats this exit code as a success and move on. The only question I have is this exit code should by default be accepted or whether we disable the handler by default and have the caller enable it when they know they are happy with this result. This functionality is already in there, so wouldn't require any fancy new code.

**Comment by zooks97** [comment]
I agree with your proposal to add another non-zero exit status for this case that the `PwBaseWorkChain` can treat as a success, if only so that there is a record that the calculation is not actually converged, even though it was never intended to be.

The only cases where this should be hit are when `electron_maxstep = 0` and/or `scf_must_converge = False`, and the user should really know what they're getting themselves in for if they give these.

So, I think that the exit code should be accepted by default. Otherwise, it might be a bit frustrating to face face up-stream workchains failing when you've clearly said this is ok in the calculation parameters.

**Comment by sphuber** [comment]
> Maybe this can be called `610`: `WARNING_ELECTRONIC_CONVERGENCE_NOT_REACHED`, and `6xx` error codes can be reserved for this and similar strong warnings?

Sounds good, it is just that the 600's were kind of reserved for whenever we decide to add support for molecular dynamics. Reasoning being a bit:

* `4xx`: SCF, NSCF, bands
* `5xx`: `relax` and `vc-relax`
* `6xx`: `md` and `vc-md`

So maybe we can start using `7xx` for warnings?

**Comment by mbercx** [comment]
> * `4xx`: SCF, NSCF, bands
> * `5xx`: `relax` and `vc-relax`
> * `6xx`: `md` and `vc-md`
> 
> So maybe we can start using `7xx` for warnings?

Just a quick note: Are these conventions already documented somewhere?

**Comment by sphuber** [comment]
This is a `aiida-quantumespresso` specific convention and is not really documented anywhere. Add it to the list for the documentation rewrite :) [There is this convention for `aiida-core`](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html#exit-code-conventions) in the documentation.

**Comment by mbercx** [comment]
> This is a `aiida-quantumespresso` specific convention and is not really documented anywhere. Add it to the list for the documentation rewrite :) [There is this convention for `aiida-core`](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html#exit-code-conventions) in the documentation.

Indeed! Opened #700
