### ISSUE TITLE
Remove parsing state checks from calculation parsers

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida-quantumespresso#70]
As long as `parse_with_retrieve` does not store any nodes, this is just as safe and more convenient.

The check appears in at least the following locations, sometimes commented out (can safely be removed too):

* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/cp.py#L45
* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/basicpw.py#L45
* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/dos.py#L54
* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/matdyn.py#L43
* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/neb.py#L49
* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/ph.py#L37
* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/projwfc.py#L290
* https://github.com/aiidateam/aiida-quantumespresso/blob/1eccb1de407098066342ac8a277ae60272aae580/aiida_quantumespresso/parsers/q2r.py#L36

**Comment by sphuber** [comment]
The original issue that this references was [#141 in aiida_core](https://github.com/aiidateam/aiida_core/issues/141)
