### ISSUE TITLE
Submission script not executed / no output files

### ISSUE THREAD

**Issue by m-a-saleh** [aiidateam/aiida-quantumespresso#711]
I have a problem that the calculations does not start. Here is what I did:

Added a computer, and tested it:
```
label: "localhost"
hostname: "localhost"
description: "my local machine"
transport: local
scheduler: "direct"
work_dir: "/home/saleh/.aiida_run"
mpirun_command: "mpirun -np 2"
mpiprocs_per_machine: "2"
prepend_text: |
   source /opt/intel/oneapi/setvars.sh
```
Added qe-pw code:
```
label: "qe-pw-6.7"
description: "quantum_espresso v6.7"
input_plugin: "quantumespresso.pw"
on_computer: true
remote_abs_path: "/home/saleh/qe-6.7/bin/pw.x"
computer: "localhost"
prepend_text: |
   ulimit -s unlimited
append_text: " "
```
Run a test PwCalculation
`aiida-quantumespresso calculation launch pw -X qe-pw-6.7 -F SSSP/1.1/PBE/efficiency`

Got the following error:
```
07/27/2021 08:58:57 AM <47989> aiida.parser.PwParser: [ERROR] Both the stdout and XML output files could not be read or parsed.
07/27/2021 08:58:57 AM <47989> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [WARNING] output parser returned exit code<305>: Both the stdout and XML output files could not be read or parsed.
PwCalculation<111> terminated with state: finished [305] `Both the stdout and XML output files could not be read or parsed.
```

To see the output file:
`verdi calcjob outputcat 111`

I got:
```
Critical: Could not open output path "aiida.out". Exception: [Errno 2] No such file or directory: '/home/saleh/.aiida/repository/quicksetup/repository/node/06/36/a94a-72e9-4a43-9469-92e46cc62edb/path/aiida.out'
```

Exploring the `.aiida_run` directory I found no output file. The generated submission script `_aiidasubmit.sh` seems OK. I copied it to a new dir along with the `aiida.in` and the `pseudo` dir, changed its permission, and ran it manually and it works.

The exact  same problem occurs when I use `verdi shell` to submit a job.  So where is the problem?

**Comment by sphuber** [comment]
It seems like there wasn't even an output file generated. This usually means QE couldn't even be launched and there will be some error in the scheduler file (although you use the direct scheduler, which is not really a scheduler). To see that file, run `verdi calcjob output at 11 _scheduler-stderr.txt`. you can also run `verdi process report 11` to get the same plus more output. Does that show anything?

**Comment by m-a-saleh** [comment]
The `_scheduler-stderr.txt` file is empty.

Running `verdi process report 111` gives:

```verdi process report 111
*** 111: None
*** Scheduler output:
:: WARNING: setvars.sh has already been run. Skipping re-execution.
   To force a re-execution of setvars.sh, use the '--force' option.
   Using '--force' can result in excessive use of your environment variables.

*** (empty scheduler errors file)
*** 2 LOG MESSAGES:
+-> ERROR at 2021-07-27 15:58:57.163973+00:00
 | Both the stdout and XML output files could not be read or parsed.
+-> WARNING at 2021-07-27 15:58:57.167825+00:00
 | output parser returned exit code<305>: Both the stdout and XML output files could not be read or parsed.
```

**Comment by sphuber** [comment]
Can you share the content of the submit script? I suspect it wasn't run with MPI and the compiled version of pw.x expects it. The CLI has a flag `--with-mpi` which you can use to make sure MPI is used in the execution. So can you try running:
```
 aiida-quantumespresso calculation launch pw -X qe-pw-6.7 -F SSSP/1.1/PBE/efficiency --with-mpi
```

**Comment by m-a-saleh** [comment]
`verdi calcjob inputcat 111 _aiidasubmit.sh` gives :

```
#!/bin/bash
exec > _scheduler-stdout.txt
exec 2> _scheduler-stderr.txt


source /opt/intel/oneapi/setvars.sh


ulimit -s unlimited


'/home/saleh/qe-6.7/bin/pw.x' '-in' 'aiida.in'  > 'aiida.out'
```
The submission command is not prepended by `mpi -np 2` even though the computer is configured with yml that have `mpirun_command: "mpirun -np 2"` and as shown also by running `verdi computer show localhost`

However, running just `'/home/saleh/qe-6.7/bin/pw.x' '-in' 'aiida.in'  > 'aiida.out'` manually in my machine terminal generates the correct output.

Configuring another computer (localhost2) with `mpirun_command: "mpirun -np {tot_num_mpiprocs}"` and another code that uses localhost2 gives the command `'mpirun' '-np' '2' '/home/saleh/qe-6.7/bin/pw.x' '-in' 'aiida.in'  > 'aiida.out' `  in the _aiidasubmit.sh (Is this a bug??), but again the damned 305 error occurs.

The flag `--with-mpi`  makes no difference in both cases (again the 305 error).

**Comment by sphuber** [comment]
> The submission command is not prepended by mpi -np 2 even though the computer is configured with yml that have mpirun_command: "mpirun -np 2" and as shown also by running verdi computer show localhost

This is because even though the MPI command is defined on the computer, you can still control to use it or not on a per-calculation level through the `metadata.options.withmpi` input, which for `PwCalculation` is apparently off by default.

> However, running just '/home/saleh/qe-6.7/bin/pw.x' '-in' 'aiida.in' > 'aiida.out' manually in my machine terminal generates the correct output.

That is indeed weird. Since AiiDA simply executes the bash script, there should be no difference. The only difference is this line `source /opt/intel/oneapi/setvars.sh`. What happens if you comment it out and do `bash _aiidaubmit.sh`. If that works, then there appears to be a problem with that custom line. I don't know what it contains and is supposed to do.

**Comment by m-a-saleh** [comment]
After removing `source /opt/intel/oneapi/setvars.sh` from the computer setup,the calculation now works (calculations finished with return code 0 and there is a correct output file).  The submission script now does not have this line.

`setvars.sh` is Intel's script to set up the environment variables to run `mpirun`, since my `pw.x` is compiled using intel performance libraries. 

There is something strange with the previous situation (i.e with `prepend_text: | source /opt/intel/oneapi/setvars.sh` . There was a warning in the `_scheduler-stderr.txt`:
```
WARNING: setvars.sh has already been run. Skipping re-execution.
```
This warning appears because I have `source /opt/intel/oneapi/setvars.sh` at my `~/.bashrc`, so the environment variables are set automatically when I start a terminal.
This warning means that `setvars.sh` was not re-executed, which should not affect the execution of the submission script by AiiDA. And as I mentioned before, executing the submission script manually runs the calculation even though the script has the line `source /opt/intel/oneapi/setvars.sh`. So does this mean there is an issue with AiiDA's ability to execute the script?? The existence of `_scheduler-stderr.txt` and `_scheduler-stdout.txt` means that AiiDA executed the script, but the absence of `aiida.out` tells that AiiDA was not to execute the line `'/home/saleh/qe-6.7/bin/pw.x' '-in' 'aiida.in'  > 'aiida.out'` in the submission script

Another thing to note:
The submission script now does not have `mpirun -np 2` prepended like before, even though the computer setup has `mpirun_command: "mpirun -np {tot_num_mpiprocs}"`, which is not a consistent behavior.

**Comment by sphuber** [comment]
Is it possible that `setvars.sh` terminates execution if executed again? This might be bubbling up to the main script and so it exits before it even comes to the `pw.x` execution line.

> Another thing to note:
The submission script now does not have mpirun -np 2 prepended like before, even though the computer setup has mpirun_command: "mpirun -np {tot_num_mpiprocs}", which is not a consistent behavior.

Why is this not consistent? Like explained before, whether the MPI run command gets prepended in the execution line depends on the `metadata.option.withmpi` input of the `CalcJob`. This may be set to `False` by default on the plugin class, and hence it will not be printed even if the computer specifies the command.
