### ISSUE TITLE
❓ Clearly define what versions of QE we support, and when we plan to drop each

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#736]
It's not entirely clear to me what versions of Quantum ESPRESSO we are meant to support with the plugin at the moment. I'm sure some older versions (<6.0) are not really supported anymore, which I think is perfectly fine since the last release of 5.X was 7 years ago.

Since the minor versions of QE often contain backwards incompatible changes, it gets more and more complex to support _all_ minor versions in one major version. We've had to add two version-specific fixes in the latest release, and going through the parsing code I find a lot of examples of other version-specific code. Generally, this makes for quite messy code that is hard to maintain.

Just wondering if we already have a policy on this. Maybe we should say that we only support the last X minor releases, or drop support for older releases within X time after the release of the next one?

**Comment by sphuber** [comment]
No, we don't have a policy on this, and it would indeed be good to come up with one. Regarding your suggestions: tying it to the number of minor releases makes it very dependent on their release speed. Maybe just having an absolute number of years that we support would be easier and more consistent?

**Comment by mbercx** [comment]
Yeah, that also seems like a more reasonable policy. Unless they don't release a new version in that amount of years and we technically don't support any version anymore at some point according to our own policy. 😁  Maybe "We vow to support the latest version of QE, as well as all older versions for up to 3 years after their release date"?

**Comment by sphuber** [comment]
> Yeah, that also seems like a more reasonable policy. Unless they don't release a new version in that amount of years and we technically don't support any version anymore at some point according to our own policy. grin Maybe "We vow to support the latest version of QE, as well as all older versions for up to 3 years after their release date"?

Think you need more than just the last version, because when that comes out it even takes us some time to provide support. I would be tempted to say something like the last three minor versions with a max of 2/3 ? years. Something to that effect.

**Comment by mbercx** [comment]
Deal! We support at least the last 3 versions. Older versions receive support for up to 2 years after their release. That would mean that from now on we only support QE v6.5 onwards and drop support for that on Dec 9th this year.

I'll probably become more intimate with the parsing codebase in the next few months, as we start adding more support for SIRIUS and the direct minimization IO. Will try to see how much can be trimmed there.

This issue can be closed once we write down this policy in the docs. Another lovely project I should really make some time for 😔 .
