### ISSUE TITLE
`PwBaseWorkChain`: error handler for diagonalization issues

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#742]
While running calculations (especially `nscf`, I've noticed), one often runs into the following errors:

1. Too many bands not converged
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
from c_bands : error # 1
too many bands are not converged
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2. Cholesky
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine  cdiaghg (161): 
      problems computing cholesky
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

[2] is already parsed and raises a specific error. [1] should also be added to the list of errors for the `PwCalculation`. For both issues, I've tried switching `ELECTRONS.diagonalization` to `'cg'`, and this was successful in fixing my `nscf` calculations ( 2 cases of [1], 12 cases of [2]). 

@pietrodelugas would you say that this is a good approach to deal with these issues in general, or did I just get lucky? 🙃 

Will be doing a lot more `PwBandsWorkChain` and `PdosWorkChain`s soon, and will try adding this error handler to see how many failures it can deal with. If it performs well, I'll open a PR.

**Comment by pietrodelugas** [comment]
No, you were not lucky,  CG is more stable 👍 ; but it is unfortunately also a lot slower 👎 .  New algorithms are now available. ParO is much faster than CG, and doesn't fail in the cases where Davidson fails.  We are also experimenting with the mixed use of the solvers (see the RMM-DIIS + ParO or RMM-DIIS + Davidson in the develop branch of QE), this might help in avoiding or recovering from failures without a too painful tradeoff in terms of performance.

**Comment by mbercx** [comment]
Thanks a lot @pietrodelugas! I'll do a bit of experimenting with `'ParO`' then, before merging #744.
