### ISSUE TITLE
Add support for QE v7.0

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#759]
The third release candidate for QE v7.0 has been tagged and is available from:

https://gitlab.com/QEF/q-e/-/tags/qe-7.0-rc1

To make sure we support this new release asap, and to see if there are any issues that we can still ask them fix before the release, I'll try to already get hold of the XML schemas and do some testing.

**Comment by sphuber** [comment]
Fixed in #774 and released with `v3.5.2`
