### ISSUE TITLE
`input_helper` broken in PyPI release - xml files missing

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-quantumespresso#765]
The latest aiida-quantumespresso release is missing the XML files for the input_helper in `aiida_quantumespresso/calculations/helpers`, see https://pypi.org/project/aiida-quantumespresso/#files

I'll open a fix for that.

**Comment by sphuber** [comment]
[Already done :)](https://github.com/aiidateam/aiida-quantumespresso/commit/a3ae4e49efda2685376afb7fac2efdd680696fea) will make a release soon

**Comment by chrisjsewell** [comment]
Won't happen when you move to flit 😆

**Comment by sphuber** [comment]
Just released [v3.5.1](https://pypi.org/project/aiida-quantumespresso/3.5.1/)

**Comment by ltalirz** [comment]
Thanks, Seb!
