### ISSUE TITLE
Add "shortcut" to aiida-quantumespresso PWscf tutorial?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-quantumespresso#766]
The [tutorial](https://aiida-quantumespresso.readthedocs.io/en/latest/user_guide/get_started/examples/pw_tutorial.html#launching-the-calculation) starts with a classic pw.x input file (which I find very helpful).

In order to then submit the same calculation with AiiDA, however, a new user has to read through what feels like 10+ pages of text.

May I suggest to add, directly after the pw.x input file, a compact translation of that submission into AiiDA language?
Like the [example script](https://aiida-quantumespresso.readthedocs.io/en/latest/_downloads/2dc19f2e8a6300052734f58bd000d074/pw_short_example.py) but a bit more nicely formatted.

The rest of the tutorial can stay as-is, but this way people can decide to read only the part that is relevant to them.

Thoughts @sphuber @mbercx?

Happy to open a quick draft PR.

**Comment by mbercx** [comment]
Thanks for reporting, @ltalirz! The current `aiida-quantumespresso` documentation is still most likely quite outdated, including the tutorial sections. I was considering updating this section with the "running processes" one we used for the AiiDA virtual tutorial last year:

https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/sections/running_processes/basics.html

as well as going through the previous version to see if any aspects are missing from the newer section. There is still quite a bit of explanation after the example QE input file here though, so it might be a good idea to still provide a script for running this example with AiiDA right in the first section.
