### ISSUE TITLE
QE 7.1 soon to be released

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-quantumespresso#816]
Information on the QE developers ML says that "Please take notice: the next QE 7.1 version will be hopefully released at the end of May".

I therefore suggest to start early the usual procedure to add support for this version (getting the schema etc.)?
@mbercx (or someone else)

**Comment by mbercx** [comment]
I'm on holiday the next two weeks, but happy to provide support when I'm back in action. 💪

**Comment by sphuber** [comment]
Fixed by #822
