### ISSUE TITLE
CLI broken when installed with `aiida-core==2.1`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#834]
This is because the CLI uses `aiida.cmdline.params.options.PROFILE` which was changed in `v2.1`. It now requires that the group/command it is associated with uses `VerdiContext` for the context class.

**Comment by ltalirz** [comment]
Fix in https://github.com/aiidateam/aiida-pseudo/issues/130

Maybe we should consider introducing a deprecation path in aiida-core for this?

**Comment by sphuber** [comment]
Already fixed it for this repo as well: https://github.com/aiidateam/aiida-quantumespresso/tree/fix/834/cli-verdi-context
Just hadn't opened a PR yet, since the code in `aiida-core` hasn't actually been released.

> Maybe we should consider introducing a deprecation path in aiida-core for this?

I am not sure this is actually possible. I was hoping that there aren't any packages that use the `options.PROFILE` option. Not really sure how to search for this in Github.
