### ISSUE TITLE
new release for aiida-pseudo compatibility?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-quantumespresso#885]
The last PyPI release of aiida-qe requires aiida-pseudo 0.8.0

Would be great to be able to use aiida-qe with the latest aiida-pseudo release

**Comment by sphuber** [comment]
Have already merged the commit to deal with this, just working on finalizing the release. Was hoping to get some other final things in. Will ensure that we release before the end of the week.

**Comment by ltalirz** [comment]
great, thanks!

**Comment by sphuber** [comment]
Fixed in #886 v4.2.0 is released with support for `aiida-pseudo~=1.0`. https://pypi.org/project/aiida-quantumespresso/4.2.0/
